package org.venuspj.studio.adapter.mybatis.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class EventsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table events
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table events
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table events
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public EventsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table events
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEventIdIsNull() {
            addCriterion("event_id is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("event_id is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(Integer value) {
            addCriterion("event_id =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(Integer value) {
            addCriterion("event_id <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(Integer value) {
            addCriterion("event_id >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_id >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(Integer value) {
            addCriterion("event_id <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("event_id <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<Integer> values) {
            addCriterion("event_id in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<Integer> values) {
            addCriterion("event_id not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(Integer value1, Integer value2) {
            addCriterion("event_id between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("event_id not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixIsNull() {
            addCriterion("event_name_prefix is null");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixIsNotNull() {
            addCriterion("event_name_prefix is not null");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixEqualTo(String value) {
            addCriterion("event_name_prefix =", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixNotEqualTo(String value) {
            addCriterion("event_name_prefix <>", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixGreaterThan(String value) {
            addCriterion("event_name_prefix >", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixGreaterThanOrEqualTo(String value) {
            addCriterion("event_name_prefix >=", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixLessThan(String value) {
            addCriterion("event_name_prefix <", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixLessThanOrEqualTo(String value) {
            addCriterion("event_name_prefix <=", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixLike(String value) {
            addCriterion("event_name_prefix like", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixNotLike(String value) {
            addCriterion("event_name_prefix not like", value, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixIn(List<String> values) {
            addCriterion("event_name_prefix in", values, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixNotIn(List<String> values) {
            addCriterion("event_name_prefix not in", values, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixBetween(String value1, String value2) {
            addCriterion("event_name_prefix between", value1, value2, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNamePrefixNotBetween(String value1, String value2) {
            addCriterion("event_name_prefix not between", value1, value2, "eventNamePrefix");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNull() {
            addCriterion("event_name is null");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNotNull() {
            addCriterion("event_name is not null");
            return (Criteria) this;
        }

        public Criteria andEventNameEqualTo(String value) {
            addCriterion("event_name =", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotEqualTo(String value) {
            addCriterion("event_name <>", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThan(String value) {
            addCriterion("event_name >", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThanOrEqualTo(String value) {
            addCriterion("event_name >=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThan(String value) {
            addCriterion("event_name <", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThanOrEqualTo(String value) {
            addCriterion("event_name <=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLike(String value) {
            addCriterion("event_name like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotLike(String value) {
            addCriterion("event_name not like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameIn(List<String> values) {
            addCriterion("event_name in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotIn(List<String> values) {
            addCriterion("event_name not in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameBetween(String value1, String value2) {
            addCriterion("event_name between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotBetween(String value1, String value2) {
            addCriterion("event_name not between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixIsNull() {
            addCriterion("event_name_postfix is null");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixIsNotNull() {
            addCriterion("event_name_postfix is not null");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixEqualTo(String value) {
            addCriterion("event_name_postfix =", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixNotEqualTo(String value) {
            addCriterion("event_name_postfix <>", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixGreaterThan(String value) {
            addCriterion("event_name_postfix >", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixGreaterThanOrEqualTo(String value) {
            addCriterion("event_name_postfix >=", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixLessThan(String value) {
            addCriterion("event_name_postfix <", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixLessThanOrEqualTo(String value) {
            addCriterion("event_name_postfix <=", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixLike(String value) {
            addCriterion("event_name_postfix like", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixNotLike(String value) {
            addCriterion("event_name_postfix not like", value, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixIn(List<String> values) {
            addCriterion("event_name_postfix in", values, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixNotIn(List<String> values) {
            addCriterion("event_name_postfix not in", values, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixBetween(String value1, String value2) {
            addCriterion("event_name_postfix between", value1, value2, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventNamePostfixNotBetween(String value1, String value2) {
            addCriterion("event_name_postfix not between", value1, value2, "eventNamePostfix");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeIsNull() {
            addCriterion("event_open_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeIsNotNull() {
            addCriterion("event_open_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeEqualTo(LocalDateTime value) {
            addCriterion("event_open_datetime =", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("event_open_datetime <>", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("event_open_datetime >", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_open_datetime >=", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeLessThan(LocalDateTime value) {
            addCriterion("event_open_datetime <", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_open_datetime <=", value, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeIn(List<LocalDateTime> values) {
            addCriterion("event_open_datetime in", values, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("event_open_datetime not in", values, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_open_datetime between", value1, value2, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventOpenDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_open_datetime not between", value1, value2, "eventOpenDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeIsNull() {
            addCriterion("event_start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeIsNotNull() {
            addCriterion("event_start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeEqualTo(LocalDateTime value) {
            addCriterion("event_start_datetime =", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("event_start_datetime <>", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("event_start_datetime >", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_start_datetime >=", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeLessThan(LocalDateTime value) {
            addCriterion("event_start_datetime <", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_start_datetime <=", value, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeIn(List<LocalDateTime> values) {
            addCriterion("event_start_datetime in", values, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("event_start_datetime not in", values, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_start_datetime between", value1, value2, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventStartDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_start_datetime not between", value1, value2, "eventStartDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeIsNull() {
            addCriterion("event_end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeIsNotNull() {
            addCriterion("event_end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeEqualTo(LocalDateTime value) {
            addCriterion("event_end_datetime =", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("event_end_datetime <>", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("event_end_datetime >", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_end_datetime >=", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeLessThan(LocalDateTime value) {
            addCriterion("event_end_datetime <", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("event_end_datetime <=", value, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeIn(List<LocalDateTime> values) {
            addCriterion("event_end_datetime in", values, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("event_end_datetime not in", values, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_end_datetime between", value1, value2, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andEventEndDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("event_end_datetime not between", value1, value2, "eventEndDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table events
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table events
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}