package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Events implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_id
     *
     * @mbg.generated
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_name_prefix
     *
     * @mbg.generated
     */
    private String eventNamePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_name_postfix
     *
     * @mbg.generated
     */
    private String eventNamePostfix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_open_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime eventOpenDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_start_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime eventStartDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_end_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime eventEndDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_description
     *
     * @mbg.generated
     */
    private String eventDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table events
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_id
     *
     * @return the value of events.event_id
     *
     * @mbg.generated
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_id
     *
     * @param eventId the value for events.event_id
     *
     * @mbg.generated
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_name_prefix
     *
     * @return the value of events.event_name_prefix
     *
     * @mbg.generated
     */
    public String getEventNamePrefix() {
        return eventNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_name_prefix
     *
     * @param eventNamePrefix the value for events.event_name_prefix
     *
     * @mbg.generated
     */
    public void setEventNamePrefix(String eventNamePrefix) {
        this.eventNamePrefix = eventNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_name
     *
     * @return the value of events.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_name
     *
     * @param eventName the value for events.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_name_postfix
     *
     * @return the value of events.event_name_postfix
     *
     * @mbg.generated
     */
    public String getEventNamePostfix() {
        return eventNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_name_postfix
     *
     * @param eventNamePostfix the value for events.event_name_postfix
     *
     * @mbg.generated
     */
    public void setEventNamePostfix(String eventNamePostfix) {
        this.eventNamePostfix = eventNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_open_datetime
     *
     * @return the value of events.event_open_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getEventOpenDatetime() {
        return eventOpenDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_open_datetime
     *
     * @param eventOpenDatetime the value for events.event_open_datetime
     *
     * @mbg.generated
     */
    public void setEventOpenDatetime(LocalDateTime eventOpenDatetime) {
        this.eventOpenDatetime = eventOpenDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_start_datetime
     *
     * @return the value of events.event_start_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getEventStartDatetime() {
        return eventStartDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_start_datetime
     *
     * @param eventStartDatetime the value for events.event_start_datetime
     *
     * @mbg.generated
     */
    public void setEventStartDatetime(LocalDateTime eventStartDatetime) {
        this.eventStartDatetime = eventStartDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_end_datetime
     *
     * @return the value of events.event_end_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getEventEndDatetime() {
        return eventEndDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_end_datetime
     *
     * @param eventEndDatetime the value for events.event_end_datetime
     *
     * @mbg.generated
     */
    public void setEventEndDatetime(LocalDateTime eventEndDatetime) {
        this.eventEndDatetime = eventEndDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.created_at
     *
     * @return the value of events.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.created_at
     *
     * @param createdAt the value for events.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.created_by
     *
     * @return the value of events.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.created_by
     *
     * @param createdBy the value for events.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_description
     *
     * @return the value of events.event_description
     *
     * @mbg.generated
     */
    public String getEventDescription() {
        return eventDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_description
     *
     * @param eventDescription the value for events.event_description
     *
     * @mbg.generated
     */
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventId=").append(eventId);
        sb.append(", eventNamePrefix=").append(eventNamePrefix);
        sb.append(", eventName=").append(eventName);
        sb.append(", eventNamePostfix=").append(eventNamePostfix);
        sb.append(", eventOpenDatetime=").append(eventOpenDatetime);
        sb.append(", eventStartDatetime=").append(eventStartDatetime);
        sb.append(", eventEndDatetime=").append(eventEndDatetime);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", eventDescription=").append(eventDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Events other = (Events) that;
        return (this.getEventId() == null ? other.getEventId() == null : this.getEventId().equals(other.getEventId()))
            && (this.getEventNamePrefix() == null ? other.getEventNamePrefix() == null : this.getEventNamePrefix().equals(other.getEventNamePrefix()))
            && (this.getEventName() == null ? other.getEventName() == null : this.getEventName().equals(other.getEventName()))
            && (this.getEventNamePostfix() == null ? other.getEventNamePostfix() == null : this.getEventNamePostfix().equals(other.getEventNamePostfix()))
            && (this.getEventOpenDatetime() == null ? other.getEventOpenDatetime() == null : this.getEventOpenDatetime().equals(other.getEventOpenDatetime()))
            && (this.getEventStartDatetime() == null ? other.getEventStartDatetime() == null : this.getEventStartDatetime().equals(other.getEventStartDatetime()))
            && (this.getEventEndDatetime() == null ? other.getEventEndDatetime() == null : this.getEventEndDatetime().equals(other.getEventEndDatetime()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getEventDescription() == null ? other.getEventDescription() == null : this.getEventDescription().equals(other.getEventDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEventId() == null) ? 0 : getEventId().hashCode());
        result = prime * result + ((getEventNamePrefix() == null) ? 0 : getEventNamePrefix().hashCode());
        result = prime * result + ((getEventName() == null) ? 0 : getEventName().hashCode());
        result = prime * result + ((getEventNamePostfix() == null) ? 0 : getEventNamePostfix().hashCode());
        result = prime * result + ((getEventOpenDatetime() == null) ? 0 : getEventOpenDatetime().hashCode());
        result = prime * result + ((getEventStartDatetime() == null) ? 0 : getEventStartDatetime().hashCode());
        result = prime * result + ((getEventEndDatetime() == null) ? 0 : getEventEndDatetime().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getEventDescription() == null) ? 0 : getEventDescription().hashCode());
        return result;
    }
}