package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Links implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_id
     *
     * @mbg.generated
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_name
     *
     * @mbg.generated
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_uri
     *
     * @mbg.generated
     */
    private String linkUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_kind
     *
     * @mbg.generated
     */
    private String linkKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table links
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_id
     *
     * @return the value of links.link_id
     *
     * @mbg.generated
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_id
     *
     * @param linkId the value for links.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_name
     *
     * @return the value of links.link_name
     *
     * @mbg.generated
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_name
     *
     * @param linkName the value for links.link_name
     *
     * @mbg.generated
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_uri
     *
     * @return the value of links.link_uri
     *
     * @mbg.generated
     */
    public String getLinkUri() {
        return linkUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_uri
     *
     * @param linkUri the value for links.link_uri
     *
     * @mbg.generated
     */
    public void setLinkUri(String linkUri) {
        this.linkUri = linkUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_kind
     *
     * @return the value of links.link_kind
     *
     * @mbg.generated
     */
    public String getLinkKind() {
        return linkKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_kind
     *
     * @param linkKind the value for links.link_kind
     *
     * @mbg.generated
     */
    public void setLinkKind(String linkKind) {
        this.linkKind = linkKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.created_at
     *
     * @return the value of links.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.created_at
     *
     * @param createdAt the value for links.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.created_by
     *
     * @return the value of links.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.created_by
     *
     * @param createdBy the value for links.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", linkId=").append(linkId);
        sb.append(", linkName=").append(linkName);
        sb.append(", linkUri=").append(linkUri);
        sb.append(", linkKind=").append(linkKind);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Links other = (Links) that;
        return (this.getLinkId() == null ? other.getLinkId() == null : this.getLinkId().equals(other.getLinkId()))
            && (this.getLinkName() == null ? other.getLinkName() == null : this.getLinkName().equals(other.getLinkName()))
            && (this.getLinkUri() == null ? other.getLinkUri() == null : this.getLinkUri().equals(other.getLinkUri()))
            && (this.getLinkKind() == null ? other.getLinkKind() == null : this.getLinkKind().equals(other.getLinkKind()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLinkId() == null) ? 0 : getLinkId().hashCode());
        result = prime * result + ((getLinkName() == null) ? 0 : getLinkName().hashCode());
        result = prime * result + ((getLinkUri() == null) ? 0 : getLinkUri().hashCode());
        result = prime * result + ((getLinkKind() == null) ? 0 : getLinkKind().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        return result;
    }
}