package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

public class News implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.topic_id
     *
     * @mbg.generated
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.topic_name
     *
     * @mbg.generated
     */
    private String topicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.topic_record_date
     *
     * @mbg.generated
     */
    private Date topicRecordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.topic_publish_date
     *
     * @mbg.generated
     */
    private Date topicPublishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.topic_description
     *
     * @mbg.generated
     */
    private String topicDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.topic_id
     *
     * @return the value of news.topic_id
     *
     * @mbg.generated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.topic_id
     *
     * @param topicId the value for news.topic_id
     *
     * @mbg.generated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.topic_name
     *
     * @return the value of news.topic_name
     *
     * @mbg.generated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.topic_name
     *
     * @param topicName the value for news.topic_name
     *
     * @mbg.generated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.topic_record_date
     *
     * @return the value of news.topic_record_date
     *
     * @mbg.generated
     */
    public Date getTopicRecordDate() {
        return topicRecordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.topic_record_date
     *
     * @param topicRecordDate the value for news.topic_record_date
     *
     * @mbg.generated
     */
    public void setTopicRecordDate(Date topicRecordDate) {
        this.topicRecordDate = topicRecordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.topic_publish_date
     *
     * @return the value of news.topic_publish_date
     *
     * @mbg.generated
     */
    public Date getTopicPublishDate() {
        return topicPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.topic_publish_date
     *
     * @param topicPublishDate the value for news.topic_publish_date
     *
     * @mbg.generated
     */
    public void setTopicPublishDate(Date topicPublishDate) {
        this.topicPublishDate = topicPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.created_at
     *
     * @return the value of news.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.created_at
     *
     * @param createdAt the value for news.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.created_by
     *
     * @return the value of news.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.created_by
     *
     * @param createdBy the value for news.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.topic_description
     *
     * @return the value of news.topic_description
     *
     * @mbg.generated
     */
    public String getTopicDescription() {
        return topicDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.topic_description
     *
     * @param topicDescription the value for news.topic_description
     *
     * @mbg.generated
     */
    public void setTopicDescription(String topicDescription) {
        this.topicDescription = topicDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", topicId=").append(topicId);
        sb.append(", topicName=").append(topicName);
        sb.append(", topicRecordDate=").append(topicRecordDate);
        sb.append(", topicPublishDate=").append(topicPublishDate);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", topicDescription=").append(topicDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        News other = (News) that;
        return (this.getTopicId() == null ? other.getTopicId() == null : this.getTopicId().equals(other.getTopicId()))
            && (this.getTopicName() == null ? other.getTopicName() == null : this.getTopicName().equals(other.getTopicName()))
            && (this.getTopicRecordDate() == null ? other.getTopicRecordDate() == null : this.getTopicRecordDate().equals(other.getTopicRecordDate()))
            && (this.getTopicPublishDate() == null ? other.getTopicPublishDate() == null : this.getTopicPublishDate().equals(other.getTopicPublishDate()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getTopicDescription() == null ? other.getTopicDescription() == null : this.getTopicDescription().equals(other.getTopicDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTopicId() == null) ? 0 : getTopicId().hashCode());
        result = prime * result + ((getTopicName() == null) ? 0 : getTopicName().hashCode());
        result = prime * result + ((getTopicRecordDate() == null) ? 0 : getTopicRecordDate().hashCode());
        result = prime * result + ((getTopicPublishDate() == null) ? 0 : getTopicPublishDate().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getTopicDescription() == null) ? 0 : getTopicDescription().hashCode());
        return result;
    }
}