package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Studios implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_id
     *
     * @mbg.generated
     */
    private String studioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_name_prefix
     *
     * @mbg.generated
     */
    private String studioNamePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_name
     *
     * @mbg.generated
     */
    private String studioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_name_postfix
     *
     * @mbg.generated
     */
    private String studioNamePostfix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_twitter
     *
     * @mbg.generated
     */
    private String studioTwitter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_short_description
     *
     * @mbg.generated
     */
    private String studioShortDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studios.studio_description
     *
     * @mbg.generated
     */
    private String studioDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studios
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_id
     *
     * @return the value of studios.studio_id
     *
     * @mbg.generated
     */
    public String getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_id
     *
     * @param studioId the value for studios.studio_id
     *
     * @mbg.generated
     */
    public void setStudioId(String studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_name_prefix
     *
     * @return the value of studios.studio_name_prefix
     *
     * @mbg.generated
     */
    public String getStudioNamePrefix() {
        return studioNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_name_prefix
     *
     * @param studioNamePrefix the value for studios.studio_name_prefix
     *
     * @mbg.generated
     */
    public void setStudioNamePrefix(String studioNamePrefix) {
        this.studioNamePrefix = studioNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_name
     *
     * @return the value of studios.studio_name
     *
     * @mbg.generated
     */
    public String getStudioName() {
        return studioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_name
     *
     * @param studioName the value for studios.studio_name
     *
     * @mbg.generated
     */
    public void setStudioName(String studioName) {
        this.studioName = studioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_name_postfix
     *
     * @return the value of studios.studio_name_postfix
     *
     * @mbg.generated
     */
    public String getStudioNamePostfix() {
        return studioNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_name_postfix
     *
     * @param studioNamePostfix the value for studios.studio_name_postfix
     *
     * @mbg.generated
     */
    public void setStudioNamePostfix(String studioNamePostfix) {
        this.studioNamePostfix = studioNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_twitter
     *
     * @return the value of studios.studio_twitter
     *
     * @mbg.generated
     */
    public String getStudioTwitter() {
        return studioTwitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_twitter
     *
     * @param studioTwitter the value for studios.studio_twitter
     *
     * @mbg.generated
     */
    public void setStudioTwitter(String studioTwitter) {
        this.studioTwitter = studioTwitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.created_at
     *
     * @return the value of studios.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.created_at
     *
     * @param createdAt the value for studios.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.created_by
     *
     * @return the value of studios.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.created_by
     *
     * @param createdBy the value for studios.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_short_description
     *
     * @return the value of studios.studio_short_description
     *
     * @mbg.generated
     */
    public String getStudioShortDescription() {
        return studioShortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_short_description
     *
     * @param studioShortDescription the value for studios.studio_short_description
     *
     * @mbg.generated
     */
    public void setStudioShortDescription(String studioShortDescription) {
        this.studioShortDescription = studioShortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studios.studio_description
     *
     * @return the value of studios.studio_description
     *
     * @mbg.generated
     */
    public String getStudioDescription() {
        return studioDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studios.studio_description
     *
     * @param studioDescription the value for studios.studio_description
     *
     * @mbg.generated
     */
    public void setStudioDescription(String studioDescription) {
        this.studioDescription = studioDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studioId=").append(studioId);
        sb.append(", studioNamePrefix=").append(studioNamePrefix);
        sb.append(", studioName=").append(studioName);
        sb.append(", studioNamePostfix=").append(studioNamePostfix);
        sb.append(", studioTwitter=").append(studioTwitter);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", studioShortDescription=").append(studioShortDescription);
        sb.append(", studioDescription=").append(studioDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Studios other = (Studios) that;
        return (this.getStudioId() == null ? other.getStudioId() == null : this.getStudioId().equals(other.getStudioId()))
            && (this.getStudioNamePrefix() == null ? other.getStudioNamePrefix() == null : this.getStudioNamePrefix().equals(other.getStudioNamePrefix()))
            && (this.getStudioName() == null ? other.getStudioName() == null : this.getStudioName().equals(other.getStudioName()))
            && (this.getStudioNamePostfix() == null ? other.getStudioNamePostfix() == null : this.getStudioNamePostfix().equals(other.getStudioNamePostfix()))
            && (this.getStudioTwitter() == null ? other.getStudioTwitter() == null : this.getStudioTwitter().equals(other.getStudioTwitter()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getStudioShortDescription() == null ? other.getStudioShortDescription() == null : this.getStudioShortDescription().equals(other.getStudioShortDescription()))
            && (this.getStudioDescription() == null ? other.getStudioDescription() == null : this.getStudioDescription().equals(other.getStudioDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStudioId() == null) ? 0 : getStudioId().hashCode());
        result = prime * result + ((getStudioNamePrefix() == null) ? 0 : getStudioNamePrefix().hashCode());
        result = prime * result + ((getStudioName() == null) ? 0 : getStudioName().hashCode());
        result = prime * result + ((getStudioNamePostfix() == null) ? 0 : getStudioNamePostfix().hashCode());
        result = prime * result + ((getStudioTwitter() == null) ? 0 : getStudioTwitter().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getStudioShortDescription() == null) ? 0 : getStudioShortDescription().hashCode());
        result = prime * result + ((getStudioDescription() == null) ? 0 : getStudioDescription().hashCode());
        return result;
    }
}