package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class StudioPlayers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_id
     *
     * @mbg.generated
     */
    private String studioPlayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.player_id
     *
     * @mbg.generated
     */
    private String playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_path
     *
     * @mbg.generated
     */
    private String studioPlayerPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_name_prefix
     *
     * @mbg.generated
     */
    private String studioPlayerNamePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_name_postfix
     *
     * @mbg.generated
     */
    private String studioPlayerNamePostfix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.display_order_number
     *
     * @mbg.generated
     */
    private Integer displayOrderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_short_description
     *
     * @mbg.generated
     */
    private String studioPlayerShortDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_players.studio_player_description
     *
     * @mbg.generated
     */
    private String studioPlayerDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_id
     *
     * @return the value of studio_players.studio_player_id
     *
     * @mbg.generated
     */
    public String getStudioPlayerId() {
        return studioPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_id
     *
     * @param studioPlayerId the value for studio_players.studio_player_id
     *
     * @mbg.generated
     */
    public void setStudioPlayerId(String studioPlayerId) {
        this.studioPlayerId = studioPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.player_id
     *
     * @return the value of studio_players.player_id
     *
     * @mbg.generated
     */
    public String getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.player_id
     *
     * @param playerId the value for studio_players.player_id
     *
     * @mbg.generated
     */
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_path
     *
     * @return the value of studio_players.studio_player_path
     *
     * @mbg.generated
     */
    public String getStudioPlayerPath() {
        return studioPlayerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_path
     *
     * @param studioPlayerPath the value for studio_players.studio_player_path
     *
     * @mbg.generated
     */
    public void setStudioPlayerPath(String studioPlayerPath) {
        this.studioPlayerPath = studioPlayerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_name_prefix
     *
     * @return the value of studio_players.studio_player_name_prefix
     *
     * @mbg.generated
     */
    public String getStudioPlayerNamePrefix() {
        return studioPlayerNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_name_prefix
     *
     * @param studioPlayerNamePrefix the value for studio_players.studio_player_name_prefix
     *
     * @mbg.generated
     */
    public void setStudioPlayerNamePrefix(String studioPlayerNamePrefix) {
        this.studioPlayerNamePrefix = studioPlayerNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_name_postfix
     *
     * @return the value of studio_players.studio_player_name_postfix
     *
     * @mbg.generated
     */
    public String getStudioPlayerNamePostfix() {
        return studioPlayerNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_name_postfix
     *
     * @param studioPlayerNamePostfix the value for studio_players.studio_player_name_postfix
     *
     * @mbg.generated
     */
    public void setStudioPlayerNamePostfix(String studioPlayerNamePostfix) {
        this.studioPlayerNamePostfix = studioPlayerNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.display_order_number
     *
     * @return the value of studio_players.display_order_number
     *
     * @mbg.generated
     */
    public Integer getDisplayOrderNumber() {
        return displayOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.display_order_number
     *
     * @param displayOrderNumber the value for studio_players.display_order_number
     *
     * @mbg.generated
     */
    public void setDisplayOrderNumber(Integer displayOrderNumber) {
        this.displayOrderNumber = displayOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.created_at
     *
     * @return the value of studio_players.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.created_at
     *
     * @param createdAt the value for studio_players.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.created_by
     *
     * @return the value of studio_players.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.created_by
     *
     * @param createdBy the value for studio_players.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_short_description
     *
     * @return the value of studio_players.studio_player_short_description
     *
     * @mbg.generated
     */
    public String getStudioPlayerShortDescription() {
        return studioPlayerShortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_short_description
     *
     * @param studioPlayerShortDescription the value for studio_players.studio_player_short_description
     *
     * @mbg.generated
     */
    public void setStudioPlayerShortDescription(String studioPlayerShortDescription) {
        this.studioPlayerShortDescription = studioPlayerShortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_players.studio_player_description
     *
     * @return the value of studio_players.studio_player_description
     *
     * @mbg.generated
     */
    public String getStudioPlayerDescription() {
        return studioPlayerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_players.studio_player_description
     *
     * @param studioPlayerDescription the value for studio_players.studio_player_description
     *
     * @mbg.generated
     */
    public void setStudioPlayerDescription(String studioPlayerDescription) {
        this.studioPlayerDescription = studioPlayerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studioPlayerId=").append(studioPlayerId);
        sb.append(", playerId=").append(playerId);
        sb.append(", studioPlayerPath=").append(studioPlayerPath);
        sb.append(", studioPlayerNamePrefix=").append(studioPlayerNamePrefix);
        sb.append(", studioPlayerNamePostfix=").append(studioPlayerNamePostfix);
        sb.append(", displayOrderNumber=").append(displayOrderNumber);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", studioPlayerShortDescription=").append(studioPlayerShortDescription);
        sb.append(", studioPlayerDescription=").append(studioPlayerDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StudioPlayers other = (StudioPlayers) that;
        return (this.getStudioPlayerId() == null ? other.getStudioPlayerId() == null : this.getStudioPlayerId().equals(other.getStudioPlayerId()))
            && (this.getPlayerId() == null ? other.getPlayerId() == null : this.getPlayerId().equals(other.getPlayerId()))
            && (this.getStudioPlayerPath() == null ? other.getStudioPlayerPath() == null : this.getStudioPlayerPath().equals(other.getStudioPlayerPath()))
            && (this.getStudioPlayerNamePrefix() == null ? other.getStudioPlayerNamePrefix() == null : this.getStudioPlayerNamePrefix().equals(other.getStudioPlayerNamePrefix()))
            && (this.getStudioPlayerNamePostfix() == null ? other.getStudioPlayerNamePostfix() == null : this.getStudioPlayerNamePostfix().equals(other.getStudioPlayerNamePostfix()))
            && (this.getDisplayOrderNumber() == null ? other.getDisplayOrderNumber() == null : this.getDisplayOrderNumber().equals(other.getDisplayOrderNumber()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getStudioPlayerShortDescription() == null ? other.getStudioPlayerShortDescription() == null : this.getStudioPlayerShortDescription().equals(other.getStudioPlayerShortDescription()))
            && (this.getStudioPlayerDescription() == null ? other.getStudioPlayerDescription() == null : this.getStudioPlayerDescription().equals(other.getStudioPlayerDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStudioPlayerId() == null) ? 0 : getStudioPlayerId().hashCode());
        result = prime * result + ((getPlayerId() == null) ? 0 : getPlayerId().hashCode());
        result = prime * result + ((getStudioPlayerPath() == null) ? 0 : getStudioPlayerPath().hashCode());
        result = prime * result + ((getStudioPlayerNamePrefix() == null) ? 0 : getStudioPlayerNamePrefix().hashCode());
        result = prime * result + ((getStudioPlayerNamePostfix() == null) ? 0 : getStudioPlayerNamePostfix().hashCode());
        result = prime * result + ((getDisplayOrderNumber() == null) ? 0 : getDisplayOrderNumber().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getStudioPlayerShortDescription() == null) ? 0 : getStudioPlayerShortDescription().hashCode());
        result = prime * result + ((getStudioPlayerDescription() == null) ? 0 : getStudioPlayerDescription().hashCode());
        return result;
    }
}