package org.venuspj.studio.adapter.mybatis.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class StudiosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studios
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studios
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studios
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public StudiosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studios
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studios
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStudioIdIsNull() {
            addCriterion("studio_id is null");
            return (Criteria) this;
        }

        public Criteria andStudioIdIsNotNull() {
            addCriterion("studio_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudioIdEqualTo(String value) {
            addCriterion("studio_id =", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdNotEqualTo(String value) {
            addCriterion("studio_id <>", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdGreaterThan(String value) {
            addCriterion("studio_id >", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdGreaterThanOrEqualTo(String value) {
            addCriterion("studio_id >=", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdLessThan(String value) {
            addCriterion("studio_id <", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdLessThanOrEqualTo(String value) {
            addCriterion("studio_id <=", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdLike(String value) {
            addCriterion("studio_id like", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdNotLike(String value) {
            addCriterion("studio_id not like", value, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdIn(List<String> values) {
            addCriterion("studio_id in", values, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdNotIn(List<String> values) {
            addCriterion("studio_id not in", values, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdBetween(String value1, String value2) {
            addCriterion("studio_id between", value1, value2, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioIdNotBetween(String value1, String value2) {
            addCriterion("studio_id not between", value1, value2, "studioId");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixIsNull() {
            addCriterion("studio_name_prefix is null");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixIsNotNull() {
            addCriterion("studio_name_prefix is not null");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixEqualTo(String value) {
            addCriterion("studio_name_prefix =", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixNotEqualTo(String value) {
            addCriterion("studio_name_prefix <>", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixGreaterThan(String value) {
            addCriterion("studio_name_prefix >", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixGreaterThanOrEqualTo(String value) {
            addCriterion("studio_name_prefix >=", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixLessThan(String value) {
            addCriterion("studio_name_prefix <", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixLessThanOrEqualTo(String value) {
            addCriterion("studio_name_prefix <=", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixLike(String value) {
            addCriterion("studio_name_prefix like", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixNotLike(String value) {
            addCriterion("studio_name_prefix not like", value, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixIn(List<String> values) {
            addCriterion("studio_name_prefix in", values, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixNotIn(List<String> values) {
            addCriterion("studio_name_prefix not in", values, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixBetween(String value1, String value2) {
            addCriterion("studio_name_prefix between", value1, value2, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePrefixNotBetween(String value1, String value2) {
            addCriterion("studio_name_prefix not between", value1, value2, "studioNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioNameIsNull() {
            addCriterion("studio_name is null");
            return (Criteria) this;
        }

        public Criteria andStudioNameIsNotNull() {
            addCriterion("studio_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudioNameEqualTo(String value) {
            addCriterion("studio_name =", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameNotEqualTo(String value) {
            addCriterion("studio_name <>", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameGreaterThan(String value) {
            addCriterion("studio_name >", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameGreaterThanOrEqualTo(String value) {
            addCriterion("studio_name >=", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameLessThan(String value) {
            addCriterion("studio_name <", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameLessThanOrEqualTo(String value) {
            addCriterion("studio_name <=", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameLike(String value) {
            addCriterion("studio_name like", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameNotLike(String value) {
            addCriterion("studio_name not like", value, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameIn(List<String> values) {
            addCriterion("studio_name in", values, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameNotIn(List<String> values) {
            addCriterion("studio_name not in", values, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameBetween(String value1, String value2) {
            addCriterion("studio_name between", value1, value2, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNameNotBetween(String value1, String value2) {
            addCriterion("studio_name not between", value1, value2, "studioName");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixIsNull() {
            addCriterion("studio_name_postfix is null");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixIsNotNull() {
            addCriterion("studio_name_postfix is not null");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixEqualTo(String value) {
            addCriterion("studio_name_postfix =", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixNotEqualTo(String value) {
            addCriterion("studio_name_postfix <>", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixGreaterThan(String value) {
            addCriterion("studio_name_postfix >", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixGreaterThanOrEqualTo(String value) {
            addCriterion("studio_name_postfix >=", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixLessThan(String value) {
            addCriterion("studio_name_postfix <", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixLessThanOrEqualTo(String value) {
            addCriterion("studio_name_postfix <=", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixLike(String value) {
            addCriterion("studio_name_postfix like", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixNotLike(String value) {
            addCriterion("studio_name_postfix not like", value, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixIn(List<String> values) {
            addCriterion("studio_name_postfix in", values, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixNotIn(List<String> values) {
            addCriterion("studio_name_postfix not in", values, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixBetween(String value1, String value2) {
            addCriterion("studio_name_postfix between", value1, value2, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioNamePostfixNotBetween(String value1, String value2) {
            addCriterion("studio_name_postfix not between", value1, value2, "studioNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterIsNull() {
            addCriterion("studio_twitter is null");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterIsNotNull() {
            addCriterion("studio_twitter is not null");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterEqualTo(String value) {
            addCriterion("studio_twitter =", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterNotEqualTo(String value) {
            addCriterion("studio_twitter <>", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterGreaterThan(String value) {
            addCriterion("studio_twitter >", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterGreaterThanOrEqualTo(String value) {
            addCriterion("studio_twitter >=", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterLessThan(String value) {
            addCriterion("studio_twitter <", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterLessThanOrEqualTo(String value) {
            addCriterion("studio_twitter <=", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterLike(String value) {
            addCriterion("studio_twitter like", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterNotLike(String value) {
            addCriterion("studio_twitter not like", value, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterIn(List<String> values) {
            addCriterion("studio_twitter in", values, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterNotIn(List<String> values) {
            addCriterion("studio_twitter not in", values, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterBetween(String value1, String value2) {
            addCriterion("studio_twitter between", value1, value2, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andStudioTwitterNotBetween(String value1, String value2) {
            addCriterion("studio_twitter not between", value1, value2, "studioTwitter");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studios
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studios
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}