package org.venuspj.studio.adapter.mybatis.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class StudioPlayersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public StudioPlayersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStudioPlayerIdIsNull() {
            addCriterion("studio_player_id is null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdIsNotNull() {
            addCriterion("studio_player_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdEqualTo(String value) {
            addCriterion("studio_player_id =", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdNotEqualTo(String value) {
            addCriterion("studio_player_id <>", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdGreaterThan(String value) {
            addCriterion("studio_player_id >", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("studio_player_id >=", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdLessThan(String value) {
            addCriterion("studio_player_id <", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdLessThanOrEqualTo(String value) {
            addCriterion("studio_player_id <=", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdLike(String value) {
            addCriterion("studio_player_id like", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdNotLike(String value) {
            addCriterion("studio_player_id not like", value, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdIn(List<String> values) {
            addCriterion("studio_player_id in", values, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdNotIn(List<String> values) {
            addCriterion("studio_player_id not in", values, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdBetween(String value1, String value2) {
            addCriterion("studio_player_id between", value1, value2, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerIdNotBetween(String value1, String value2) {
            addCriterion("studio_player_id not between", value1, value2, "studioPlayerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNull() {
            addCriterion("player_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNotNull() {
            addCriterion("player_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdEqualTo(String value) {
            addCriterion("player_id =", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotEqualTo(String value) {
            addCriterion("player_id <>", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThan(String value) {
            addCriterion("player_id >", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("player_id >=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThan(String value) {
            addCriterion("player_id <", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThanOrEqualTo(String value) {
            addCriterion("player_id <=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLike(String value) {
            addCriterion("player_id like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotLike(String value) {
            addCriterion("player_id not like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIn(List<String> values) {
            addCriterion("player_id in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotIn(List<String> values) {
            addCriterion("player_id not in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdBetween(String value1, String value2) {
            addCriterion("player_id between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotBetween(String value1, String value2) {
            addCriterion("player_id not between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathIsNull() {
            addCriterion("studio_player_path is null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathIsNotNull() {
            addCriterion("studio_player_path is not null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathEqualTo(String value) {
            addCriterion("studio_player_path =", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathNotEqualTo(String value) {
            addCriterion("studio_player_path <>", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathGreaterThan(String value) {
            addCriterion("studio_player_path >", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathGreaterThanOrEqualTo(String value) {
            addCriterion("studio_player_path >=", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathLessThan(String value) {
            addCriterion("studio_player_path <", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathLessThanOrEqualTo(String value) {
            addCriterion("studio_player_path <=", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathLike(String value) {
            addCriterion("studio_player_path like", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathNotLike(String value) {
            addCriterion("studio_player_path not like", value, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathIn(List<String> values) {
            addCriterion("studio_player_path in", values, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathNotIn(List<String> values) {
            addCriterion("studio_player_path not in", values, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathBetween(String value1, String value2) {
            addCriterion("studio_player_path between", value1, value2, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerPathNotBetween(String value1, String value2) {
            addCriterion("studio_player_path not between", value1, value2, "studioPlayerPath");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixIsNull() {
            addCriterion("studio_player_name_prefix is null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixIsNotNull() {
            addCriterion("studio_player_name_prefix is not null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixEqualTo(String value) {
            addCriterion("studio_player_name_prefix =", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixNotEqualTo(String value) {
            addCriterion("studio_player_name_prefix <>", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixGreaterThan(String value) {
            addCriterion("studio_player_name_prefix >", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixGreaterThanOrEqualTo(String value) {
            addCriterion("studio_player_name_prefix >=", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixLessThan(String value) {
            addCriterion("studio_player_name_prefix <", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixLessThanOrEqualTo(String value) {
            addCriterion("studio_player_name_prefix <=", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixLike(String value) {
            addCriterion("studio_player_name_prefix like", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixNotLike(String value) {
            addCriterion("studio_player_name_prefix not like", value, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixIn(List<String> values) {
            addCriterion("studio_player_name_prefix in", values, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixNotIn(List<String> values) {
            addCriterion("studio_player_name_prefix not in", values, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixBetween(String value1, String value2) {
            addCriterion("studio_player_name_prefix between", value1, value2, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePrefixNotBetween(String value1, String value2) {
            addCriterion("studio_player_name_prefix not between", value1, value2, "studioPlayerNamePrefix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixIsNull() {
            addCriterion("studio_player_name_postfix is null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixIsNotNull() {
            addCriterion("studio_player_name_postfix is not null");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixEqualTo(String value) {
            addCriterion("studio_player_name_postfix =", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixNotEqualTo(String value) {
            addCriterion("studio_player_name_postfix <>", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixGreaterThan(String value) {
            addCriterion("studio_player_name_postfix >", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixGreaterThanOrEqualTo(String value) {
            addCriterion("studio_player_name_postfix >=", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixLessThan(String value) {
            addCriterion("studio_player_name_postfix <", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixLessThanOrEqualTo(String value) {
            addCriterion("studio_player_name_postfix <=", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixLike(String value) {
            addCriterion("studio_player_name_postfix like", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixNotLike(String value) {
            addCriterion("studio_player_name_postfix not like", value, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixIn(List<String> values) {
            addCriterion("studio_player_name_postfix in", values, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixNotIn(List<String> values) {
            addCriterion("studio_player_name_postfix not in", values, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixBetween(String value1, String value2) {
            addCriterion("studio_player_name_postfix between", value1, value2, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andStudioPlayerNamePostfixNotBetween(String value1, String value2) {
            addCriterion("studio_player_name_postfix not between", value1, value2, "studioPlayerNamePostfix");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberIsNull() {
            addCriterion("display_order_number is null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberIsNotNull() {
            addCriterion("display_order_number is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberEqualTo(Integer value) {
            addCriterion("display_order_number =", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberNotEqualTo(Integer value) {
            addCriterion("display_order_number <>", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberGreaterThan(Integer value) {
            addCriterion("display_order_number >", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("display_order_number >=", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberLessThan(Integer value) {
            addCriterion("display_order_number <", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberLessThanOrEqualTo(Integer value) {
            addCriterion("display_order_number <=", value, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberIn(List<Integer> values) {
            addCriterion("display_order_number in", values, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberNotIn(List<Integer> values) {
            addCriterion("display_order_number not in", values, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberBetween(Integer value1, Integer value2) {
            addCriterion("display_order_number between", value1, value2, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("display_order_number not between", value1, value2, "displayOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studio_players
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}