package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class StudioPlayerMembers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_player_members.studio_player_member_id
     *
     * @mbg.generated
     */
    private String studioPlayerMemberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_player_members.studio_player_member_name
     *
     * @mbg.generated
     */
    private String studioPlayerMemberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_player_members.display_order_number
     *
     * @mbg.generated
     */
    private Integer displayOrderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_player_members.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio_player_members.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_player_members.studio_player_member_id
     *
     * @return the value of studio_player_members.studio_player_member_id
     *
     * @mbg.generated
     */
    public String getStudioPlayerMemberId() {
        return studioPlayerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_player_members.studio_player_member_id
     *
     * @param studioPlayerMemberId the value for studio_player_members.studio_player_member_id
     *
     * @mbg.generated
     */
    public void setStudioPlayerMemberId(String studioPlayerMemberId) {
        this.studioPlayerMemberId = studioPlayerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_player_members.studio_player_member_name
     *
     * @return the value of studio_player_members.studio_player_member_name
     *
     * @mbg.generated
     */
    public String getStudioPlayerMemberName() {
        return studioPlayerMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_player_members.studio_player_member_name
     *
     * @param studioPlayerMemberName the value for studio_player_members.studio_player_member_name
     *
     * @mbg.generated
     */
    public void setStudioPlayerMemberName(String studioPlayerMemberName) {
        this.studioPlayerMemberName = studioPlayerMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_player_members.display_order_number
     *
     * @return the value of studio_player_members.display_order_number
     *
     * @mbg.generated
     */
    public Integer getDisplayOrderNumber() {
        return displayOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_player_members.display_order_number
     *
     * @param displayOrderNumber the value for studio_player_members.display_order_number
     *
     * @mbg.generated
     */
    public void setDisplayOrderNumber(Integer displayOrderNumber) {
        this.displayOrderNumber = displayOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_player_members.created_at
     *
     * @return the value of studio_player_members.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_player_members.created_at
     *
     * @param createdAt the value for studio_player_members.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio_player_members.created_by
     *
     * @return the value of studio_player_members.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio_player_members.created_by
     *
     * @param createdBy the value for studio_player_members.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studioPlayerMemberId=").append(studioPlayerMemberId);
        sb.append(", studioPlayerMemberName=").append(studioPlayerMemberName);
        sb.append(", displayOrderNumber=").append(displayOrderNumber);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StudioPlayerMembers other = (StudioPlayerMembers) that;
        return (this.getStudioPlayerMemberId() == null ? other.getStudioPlayerMemberId() == null : this.getStudioPlayerMemberId().equals(other.getStudioPlayerMemberId()))
            && (this.getStudioPlayerMemberName() == null ? other.getStudioPlayerMemberName() == null : this.getStudioPlayerMemberName().equals(other.getStudioPlayerMemberName()))
            && (this.getDisplayOrderNumber() == null ? other.getDisplayOrderNumber() == null : this.getDisplayOrderNumber().equals(other.getDisplayOrderNumber()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStudioPlayerMemberId() == null) ? 0 : getStudioPlayerMemberId().hashCode());
        result = prime * result + ((getStudioPlayerMemberName() == null) ? 0 : getStudioPlayerMemberName().hashCode());
        result = prime * result + ((getDisplayOrderNumber() == null) ? 0 : getDisplayOrderNumber().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        return result;
    }
}