package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class TwitterAccounts implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twitter_accounts.twitter_accounts_id
     *
     * @mbg.generated
     */
    private Integer twitterAccountsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twitter_accounts.twitter_id
     *
     * @mbg.generated
     */
    private String twitterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twitter_accounts.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twitter_accounts.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twitter_accounts.twitter_accounts_id
     *
     * @return the value of twitter_accounts.twitter_accounts_id
     *
     * @mbg.generated
     */
    public Integer getTwitterAccountsId() {
        return twitterAccountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twitter_accounts.twitter_accounts_id
     *
     * @param twitterAccountsId the value for twitter_accounts.twitter_accounts_id
     *
     * @mbg.generated
     */
    public void setTwitterAccountsId(Integer twitterAccountsId) {
        this.twitterAccountsId = twitterAccountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twitter_accounts.twitter_id
     *
     * @return the value of twitter_accounts.twitter_id
     *
     * @mbg.generated
     */
    public String getTwitterId() {
        return twitterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twitter_accounts.twitter_id
     *
     * @param twitterId the value for twitter_accounts.twitter_id
     *
     * @mbg.generated
     */
    public void setTwitterId(String twitterId) {
        this.twitterId = twitterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twitter_accounts.created_at
     *
     * @return the value of twitter_accounts.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twitter_accounts.created_at
     *
     * @param createdAt the value for twitter_accounts.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twitter_accounts.created_by
     *
     * @return the value of twitter_accounts.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twitter_accounts.created_by
     *
     * @param createdBy the value for twitter_accounts.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", twitterAccountsId=").append(twitterAccountsId);
        sb.append(", twitterId=").append(twitterId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TwitterAccounts other = (TwitterAccounts) that;
        return (this.getTwitterAccountsId() == null ? other.getTwitterAccountsId() == null : this.getTwitterAccountsId().equals(other.getTwitterAccountsId()))
            && (this.getTwitterId() == null ? other.getTwitterId() == null : this.getTwitterId().equals(other.getTwitterId()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTwitterAccountsId() == null) ? 0 : getTwitterAccountsId().hashCode());
        result = prime * result + ((getTwitterId() == null) ? 0 : getTwitterId().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        return result;
    }
}