package org.venuspj.studio.adapter.mybatis.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Venues implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_id
     *
     * @mbg.generated
     */
    private Integer venueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_name_prefix
     *
     * @mbg.generated
     */
    private String venueNamePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_name
     *
     * @mbg.generated
     */
    private String venueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_name_postfix
     *
     * @mbg.generated
     */
    private String venueNamePostfix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_address
     *
     * @mbg.generated
     */
    private String venueAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_latitude
     *
     * @mbg.generated
     */
    private String venueLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_longitude
     *
     * @mbg.generated
     */
    private String venueLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_tel_no
     *
     * @mbg.generated
     */
    private String venueTelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_twitter
     *
     * @mbg.generated
     */
    private String venueTwitter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_email
     *
     * @mbg.generated
     */
    private String venueEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_url
     *
     * @mbg.generated
     */
    private String venueUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venue_description
     *
     * @mbg.generated
     */
    private String venueDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venues
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_id
     *
     * @return the value of venues.venue_id
     *
     * @mbg.generated
     */
    public Integer getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_id
     *
     * @param venueId the value for venues.venue_id
     *
     * @mbg.generated
     */
    public void setVenueId(Integer venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_name_prefix
     *
     * @return the value of venues.venue_name_prefix
     *
     * @mbg.generated
     */
    public String getVenueNamePrefix() {
        return venueNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_name_prefix
     *
     * @param venueNamePrefix the value for venues.venue_name_prefix
     *
     * @mbg.generated
     */
    public void setVenueNamePrefix(String venueNamePrefix) {
        this.venueNamePrefix = venueNamePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_name
     *
     * @return the value of venues.venue_name
     *
     * @mbg.generated
     */
    public String getVenueName() {
        return venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_name
     *
     * @param venueName the value for venues.venue_name
     *
     * @mbg.generated
     */
    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_name_postfix
     *
     * @return the value of venues.venue_name_postfix
     *
     * @mbg.generated
     */
    public String getVenueNamePostfix() {
        return venueNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_name_postfix
     *
     * @param venueNamePostfix the value for venues.venue_name_postfix
     *
     * @mbg.generated
     */
    public void setVenueNamePostfix(String venueNamePostfix) {
        this.venueNamePostfix = venueNamePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_address
     *
     * @return the value of venues.venue_address
     *
     * @mbg.generated
     */
    public String getVenueAddress() {
        return venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_address
     *
     * @param venueAddress the value for venues.venue_address
     *
     * @mbg.generated
     */
    public void setVenueAddress(String venueAddress) {
        this.venueAddress = venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_latitude
     *
     * @return the value of venues.venue_latitude
     *
     * @mbg.generated
     */
    public String getVenueLatitude() {
        return venueLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_latitude
     *
     * @param venueLatitude the value for venues.venue_latitude
     *
     * @mbg.generated
     */
    public void setVenueLatitude(String venueLatitude) {
        this.venueLatitude = venueLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_longitude
     *
     * @return the value of venues.venue_longitude
     *
     * @mbg.generated
     */
    public String getVenueLongitude() {
        return venueLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_longitude
     *
     * @param venueLongitude the value for venues.venue_longitude
     *
     * @mbg.generated
     */
    public void setVenueLongitude(String venueLongitude) {
        this.venueLongitude = venueLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_tel_no
     *
     * @return the value of venues.venue_tel_no
     *
     * @mbg.generated
     */
    public String getVenueTelNo() {
        return venueTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_tel_no
     *
     * @param venueTelNo the value for venues.venue_tel_no
     *
     * @mbg.generated
     */
    public void setVenueTelNo(String venueTelNo) {
        this.venueTelNo = venueTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_twitter
     *
     * @return the value of venues.venue_twitter
     *
     * @mbg.generated
     */
    public String getVenueTwitter() {
        return venueTwitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_twitter
     *
     * @param venueTwitter the value for venues.venue_twitter
     *
     * @mbg.generated
     */
    public void setVenueTwitter(String venueTwitter) {
        this.venueTwitter = venueTwitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_email
     *
     * @return the value of venues.venue_email
     *
     * @mbg.generated
     */
    public String getVenueEmail() {
        return venueEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_email
     *
     * @param venueEmail the value for venues.venue_email
     *
     * @mbg.generated
     */
    public void setVenueEmail(String venueEmail) {
        this.venueEmail = venueEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_url
     *
     * @return the value of venues.venue_url
     *
     * @mbg.generated
     */
    public String getVenueUrl() {
        return venueUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_url
     *
     * @param venueUrl the value for venues.venue_url
     *
     * @mbg.generated
     */
    public void setVenueUrl(String venueUrl) {
        this.venueUrl = venueUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.created_at
     *
     * @return the value of venues.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.created_at
     *
     * @param createdAt the value for venues.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.created_by
     *
     * @return the value of venues.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.created_by
     *
     * @param createdBy the value for venues.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venue_description
     *
     * @return the value of venues.venue_description
     *
     * @mbg.generated
     */
    public String getVenueDescription() {
        return venueDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venue_description
     *
     * @param venueDescription the value for venues.venue_description
     *
     * @mbg.generated
     */
    public void setVenueDescription(String venueDescription) {
        this.venueDescription = venueDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", venueId=").append(venueId);
        sb.append(", venueNamePrefix=").append(venueNamePrefix);
        sb.append(", venueName=").append(venueName);
        sb.append(", venueNamePostfix=").append(venueNamePostfix);
        sb.append(", venueAddress=").append(venueAddress);
        sb.append(", venueLatitude=").append(venueLatitude);
        sb.append(", venueLongitude=").append(venueLongitude);
        sb.append(", venueTelNo=").append(venueTelNo);
        sb.append(", venueTwitter=").append(venueTwitter);
        sb.append(", venueEmail=").append(venueEmail);
        sb.append(", venueUrl=").append(venueUrl);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", venueDescription=").append(venueDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Venues other = (Venues) that;
        return (this.getVenueId() == null ? other.getVenueId() == null : this.getVenueId().equals(other.getVenueId()))
            && (this.getVenueNamePrefix() == null ? other.getVenueNamePrefix() == null : this.getVenueNamePrefix().equals(other.getVenueNamePrefix()))
            && (this.getVenueName() == null ? other.getVenueName() == null : this.getVenueName().equals(other.getVenueName()))
            && (this.getVenueNamePostfix() == null ? other.getVenueNamePostfix() == null : this.getVenueNamePostfix().equals(other.getVenueNamePostfix()))
            && (this.getVenueAddress() == null ? other.getVenueAddress() == null : this.getVenueAddress().equals(other.getVenueAddress()))
            && (this.getVenueLatitude() == null ? other.getVenueLatitude() == null : this.getVenueLatitude().equals(other.getVenueLatitude()))
            && (this.getVenueLongitude() == null ? other.getVenueLongitude() == null : this.getVenueLongitude().equals(other.getVenueLongitude()))
            && (this.getVenueTelNo() == null ? other.getVenueTelNo() == null : this.getVenueTelNo().equals(other.getVenueTelNo()))
            && (this.getVenueTwitter() == null ? other.getVenueTwitter() == null : this.getVenueTwitter().equals(other.getVenueTwitter()))
            && (this.getVenueEmail() == null ? other.getVenueEmail() == null : this.getVenueEmail().equals(other.getVenueEmail()))
            && (this.getVenueUrl() == null ? other.getVenueUrl() == null : this.getVenueUrl().equals(other.getVenueUrl()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getVenueDescription() == null ? other.getVenueDescription() == null : this.getVenueDescription().equals(other.getVenueDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVenueId() == null) ? 0 : getVenueId().hashCode());
        result = prime * result + ((getVenueNamePrefix() == null) ? 0 : getVenueNamePrefix().hashCode());
        result = prime * result + ((getVenueName() == null) ? 0 : getVenueName().hashCode());
        result = prime * result + ((getVenueNamePostfix() == null) ? 0 : getVenueNamePostfix().hashCode());
        result = prime * result + ((getVenueAddress() == null) ? 0 : getVenueAddress().hashCode());
        result = prime * result + ((getVenueLatitude() == null) ? 0 : getVenueLatitude().hashCode());
        result = prime * result + ((getVenueLongitude() == null) ? 0 : getVenueLongitude().hashCode());
        result = prime * result + ((getVenueTelNo() == null) ? 0 : getVenueTelNo().hashCode());
        result = prime * result + ((getVenueTwitter() == null) ? 0 : getVenueTwitter().hashCode());
        result = prime * result + ((getVenueEmail() == null) ? 0 : getVenueEmail().hashCode());
        result = prime * result + ((getVenueUrl() == null) ? 0 : getVenueUrl().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getVenueDescription() == null) ? 0 : getVenueDescription().hashCode());
        return result;
    }
}