package org.venuspj.studio.adapter.mybatis.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class VenuesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venues
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venues
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venues
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public VenuesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venues
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVenueIdIsNull() {
            addCriterion("venue_id is null");
            return (Criteria) this;
        }

        public Criteria andVenueIdIsNotNull() {
            addCriterion("venue_id is not null");
            return (Criteria) this;
        }

        public Criteria andVenueIdEqualTo(Integer value) {
            addCriterion("venue_id =", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdNotEqualTo(Integer value) {
            addCriterion("venue_id <>", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdGreaterThan(Integer value) {
            addCriterion("venue_id >", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("venue_id >=", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdLessThan(Integer value) {
            addCriterion("venue_id <", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdLessThanOrEqualTo(Integer value) {
            addCriterion("venue_id <=", value, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdIn(List<Integer> values) {
            addCriterion("venue_id in", values, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdNotIn(List<Integer> values) {
            addCriterion("venue_id not in", values, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdBetween(Integer value1, Integer value2) {
            addCriterion("venue_id between", value1, value2, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("venue_id not between", value1, value2, "venueId");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixIsNull() {
            addCriterion("venue_name_prefix is null");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixIsNotNull() {
            addCriterion("venue_name_prefix is not null");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixEqualTo(String value) {
            addCriterion("venue_name_prefix =", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixNotEqualTo(String value) {
            addCriterion("venue_name_prefix <>", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixGreaterThan(String value) {
            addCriterion("venue_name_prefix >", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixGreaterThanOrEqualTo(String value) {
            addCriterion("venue_name_prefix >=", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixLessThan(String value) {
            addCriterion("venue_name_prefix <", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixLessThanOrEqualTo(String value) {
            addCriterion("venue_name_prefix <=", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixLike(String value) {
            addCriterion("venue_name_prefix like", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixNotLike(String value) {
            addCriterion("venue_name_prefix not like", value, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixIn(List<String> values) {
            addCriterion("venue_name_prefix in", values, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixNotIn(List<String> values) {
            addCriterion("venue_name_prefix not in", values, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixBetween(String value1, String value2) {
            addCriterion("venue_name_prefix between", value1, value2, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePrefixNotBetween(String value1, String value2) {
            addCriterion("venue_name_prefix not between", value1, value2, "venueNamePrefix");
            return (Criteria) this;
        }

        public Criteria andVenueNameIsNull() {
            addCriterion("venue_name is null");
            return (Criteria) this;
        }

        public Criteria andVenueNameIsNotNull() {
            addCriterion("venue_name is not null");
            return (Criteria) this;
        }

        public Criteria andVenueNameEqualTo(String value) {
            addCriterion("venue_name =", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameNotEqualTo(String value) {
            addCriterion("venue_name <>", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameGreaterThan(String value) {
            addCriterion("venue_name >", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameGreaterThanOrEqualTo(String value) {
            addCriterion("venue_name >=", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameLessThan(String value) {
            addCriterion("venue_name <", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameLessThanOrEqualTo(String value) {
            addCriterion("venue_name <=", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameLike(String value) {
            addCriterion("venue_name like", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameNotLike(String value) {
            addCriterion("venue_name not like", value, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameIn(List<String> values) {
            addCriterion("venue_name in", values, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameNotIn(List<String> values) {
            addCriterion("venue_name not in", values, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameBetween(String value1, String value2) {
            addCriterion("venue_name between", value1, value2, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNameNotBetween(String value1, String value2) {
            addCriterion("venue_name not between", value1, value2, "venueName");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixIsNull() {
            addCriterion("venue_name_postfix is null");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixIsNotNull() {
            addCriterion("venue_name_postfix is not null");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixEqualTo(String value) {
            addCriterion("venue_name_postfix =", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixNotEqualTo(String value) {
            addCriterion("venue_name_postfix <>", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixGreaterThan(String value) {
            addCriterion("venue_name_postfix >", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixGreaterThanOrEqualTo(String value) {
            addCriterion("venue_name_postfix >=", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixLessThan(String value) {
            addCriterion("venue_name_postfix <", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixLessThanOrEqualTo(String value) {
            addCriterion("venue_name_postfix <=", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixLike(String value) {
            addCriterion("venue_name_postfix like", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixNotLike(String value) {
            addCriterion("venue_name_postfix not like", value, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixIn(List<String> values) {
            addCriterion("venue_name_postfix in", values, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixNotIn(List<String> values) {
            addCriterion("venue_name_postfix not in", values, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixBetween(String value1, String value2) {
            addCriterion("venue_name_postfix between", value1, value2, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueNamePostfixNotBetween(String value1, String value2) {
            addCriterion("venue_name_postfix not between", value1, value2, "venueNamePostfix");
            return (Criteria) this;
        }

        public Criteria andVenueAddressIsNull() {
            addCriterion("venue_address is null");
            return (Criteria) this;
        }

        public Criteria andVenueAddressIsNotNull() {
            addCriterion("venue_address is not null");
            return (Criteria) this;
        }

        public Criteria andVenueAddressEqualTo(String value) {
            addCriterion("venue_address =", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressNotEqualTo(String value) {
            addCriterion("venue_address <>", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressGreaterThan(String value) {
            addCriterion("venue_address >", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressGreaterThanOrEqualTo(String value) {
            addCriterion("venue_address >=", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressLessThan(String value) {
            addCriterion("venue_address <", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressLessThanOrEqualTo(String value) {
            addCriterion("venue_address <=", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressLike(String value) {
            addCriterion("venue_address like", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressNotLike(String value) {
            addCriterion("venue_address not like", value, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressIn(List<String> values) {
            addCriterion("venue_address in", values, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressNotIn(List<String> values) {
            addCriterion("venue_address not in", values, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressBetween(String value1, String value2) {
            addCriterion("venue_address between", value1, value2, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueAddressNotBetween(String value1, String value2) {
            addCriterion("venue_address not between", value1, value2, "venueAddress");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeIsNull() {
            addCriterion("venue_latitude is null");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeIsNotNull() {
            addCriterion("venue_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeEqualTo(String value) {
            addCriterion("venue_latitude =", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeNotEqualTo(String value) {
            addCriterion("venue_latitude <>", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeGreaterThan(String value) {
            addCriterion("venue_latitude >", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("venue_latitude >=", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeLessThan(String value) {
            addCriterion("venue_latitude <", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeLessThanOrEqualTo(String value) {
            addCriterion("venue_latitude <=", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeLike(String value) {
            addCriterion("venue_latitude like", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeNotLike(String value) {
            addCriterion("venue_latitude not like", value, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeIn(List<String> values) {
            addCriterion("venue_latitude in", values, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeNotIn(List<String> values) {
            addCriterion("venue_latitude not in", values, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeBetween(String value1, String value2) {
            addCriterion("venue_latitude between", value1, value2, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLatitudeNotBetween(String value1, String value2) {
            addCriterion("venue_latitude not between", value1, value2, "venueLatitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeIsNull() {
            addCriterion("venue_longitude is null");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeIsNotNull() {
            addCriterion("venue_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeEqualTo(String value) {
            addCriterion("venue_longitude =", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeNotEqualTo(String value) {
            addCriterion("venue_longitude <>", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeGreaterThan(String value) {
            addCriterion("venue_longitude >", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("venue_longitude >=", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeLessThan(String value) {
            addCriterion("venue_longitude <", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeLessThanOrEqualTo(String value) {
            addCriterion("venue_longitude <=", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeLike(String value) {
            addCriterion("venue_longitude like", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeNotLike(String value) {
            addCriterion("venue_longitude not like", value, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeIn(List<String> values) {
            addCriterion("venue_longitude in", values, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeNotIn(List<String> values) {
            addCriterion("venue_longitude not in", values, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeBetween(String value1, String value2) {
            addCriterion("venue_longitude between", value1, value2, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueLongitudeNotBetween(String value1, String value2) {
            addCriterion("venue_longitude not between", value1, value2, "venueLongitude");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoIsNull() {
            addCriterion("venue_tel_no is null");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoIsNotNull() {
            addCriterion("venue_tel_no is not null");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoEqualTo(String value) {
            addCriterion("venue_tel_no =", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoNotEqualTo(String value) {
            addCriterion("venue_tel_no <>", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoGreaterThan(String value) {
            addCriterion("venue_tel_no >", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("venue_tel_no >=", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoLessThan(String value) {
            addCriterion("venue_tel_no <", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoLessThanOrEqualTo(String value) {
            addCriterion("venue_tel_no <=", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoLike(String value) {
            addCriterion("venue_tel_no like", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoNotLike(String value) {
            addCriterion("venue_tel_no not like", value, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoIn(List<String> values) {
            addCriterion("venue_tel_no in", values, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoNotIn(List<String> values) {
            addCriterion("venue_tel_no not in", values, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoBetween(String value1, String value2) {
            addCriterion("venue_tel_no between", value1, value2, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTelNoNotBetween(String value1, String value2) {
            addCriterion("venue_tel_no not between", value1, value2, "venueTelNo");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterIsNull() {
            addCriterion("venue_twitter is null");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterIsNotNull() {
            addCriterion("venue_twitter is not null");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterEqualTo(String value) {
            addCriterion("venue_twitter =", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterNotEqualTo(String value) {
            addCriterion("venue_twitter <>", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterGreaterThan(String value) {
            addCriterion("venue_twitter >", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterGreaterThanOrEqualTo(String value) {
            addCriterion("venue_twitter >=", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterLessThan(String value) {
            addCriterion("venue_twitter <", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterLessThanOrEqualTo(String value) {
            addCriterion("venue_twitter <=", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterLike(String value) {
            addCriterion("venue_twitter like", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterNotLike(String value) {
            addCriterion("venue_twitter not like", value, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterIn(List<String> values) {
            addCriterion("venue_twitter in", values, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterNotIn(List<String> values) {
            addCriterion("venue_twitter not in", values, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterBetween(String value1, String value2) {
            addCriterion("venue_twitter between", value1, value2, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueTwitterNotBetween(String value1, String value2) {
            addCriterion("venue_twitter not between", value1, value2, "venueTwitter");
            return (Criteria) this;
        }

        public Criteria andVenueEmailIsNull() {
            addCriterion("venue_email is null");
            return (Criteria) this;
        }

        public Criteria andVenueEmailIsNotNull() {
            addCriterion("venue_email is not null");
            return (Criteria) this;
        }

        public Criteria andVenueEmailEqualTo(String value) {
            addCriterion("venue_email =", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailNotEqualTo(String value) {
            addCriterion("venue_email <>", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailGreaterThan(String value) {
            addCriterion("venue_email >", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailGreaterThanOrEqualTo(String value) {
            addCriterion("venue_email >=", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailLessThan(String value) {
            addCriterion("venue_email <", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailLessThanOrEqualTo(String value) {
            addCriterion("venue_email <=", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailLike(String value) {
            addCriterion("venue_email like", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailNotLike(String value) {
            addCriterion("venue_email not like", value, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailIn(List<String> values) {
            addCriterion("venue_email in", values, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailNotIn(List<String> values) {
            addCriterion("venue_email not in", values, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailBetween(String value1, String value2) {
            addCriterion("venue_email between", value1, value2, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueEmailNotBetween(String value1, String value2) {
            addCriterion("venue_email not between", value1, value2, "venueEmail");
            return (Criteria) this;
        }

        public Criteria andVenueUrlIsNull() {
            addCriterion("venue_url is null");
            return (Criteria) this;
        }

        public Criteria andVenueUrlIsNotNull() {
            addCriterion("venue_url is not null");
            return (Criteria) this;
        }

        public Criteria andVenueUrlEqualTo(String value) {
            addCriterion("venue_url =", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlNotEqualTo(String value) {
            addCriterion("venue_url <>", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlGreaterThan(String value) {
            addCriterion("venue_url >", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlGreaterThanOrEqualTo(String value) {
            addCriterion("venue_url >=", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlLessThan(String value) {
            addCriterion("venue_url <", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlLessThanOrEqualTo(String value) {
            addCriterion("venue_url <=", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlLike(String value) {
            addCriterion("venue_url like", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlNotLike(String value) {
            addCriterion("venue_url not like", value, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlIn(List<String> values) {
            addCriterion("venue_url in", values, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlNotIn(List<String> values) {
            addCriterion("venue_url not in", values, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlBetween(String value1, String value2) {
            addCriterion("venue_url between", value1, value2, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andVenueUrlNotBetween(String value1, String value2) {
            addCriterion("venue_url not between", value1, value2, "venueUrl");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venues
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venues
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}