# Spring Core
spring:
  profiles.active: unit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studiout
    username: studio
    password: Shishi1231

mybatis:
  type-handlers-package: com.example.typehandler
