package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Links;

public interface LinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Delete({
        "delete from links",
        "where link_id = #{linkId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Insert({
        "insert into links (link_id, link_name, ",
        "link_uri, link_kind, ",
        "created_at, created_by)",
        "values (#{linkId,jdbcType=INTEGER}, #{linkName,jdbcType=VARCHAR}, ",
        "#{linkUri,jdbcType=VARCHAR}, #{linkKind,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    int insertSelective(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "link_id, link_name, link_uri, link_kind, created_at, created_by",
        "from links",
        "where link_id = #{linkId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.LinksMapper.BaseResultMap")
    Links selectByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated
     */
    @Update({
        "update links",
        "set link_name = #{linkName,jdbcType=VARCHAR},",
          "link_uri = #{linkUri,jdbcType=VARCHAR},",
          "link_kind = #{linkKind,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR}",
        "where link_id = #{linkId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Links record);
}