package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Organizations;
import org.venuspj.studio.adapter.mybatis.model.OrganizationsExample;

import java.util.List;

@Mapper
public interface OrganizationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    @Delete({
            "delete from organizations",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    @Insert({
            "insert into organizations (party_id, name, ",
            "created_at, created_by)",
            "values (#{partyId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    int insertSelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    List<Organizations> selectByExample(OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "party_id, name, created_at, created_by",
            "from organizations",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.OrganizationsMapper.BaseResultMap")
    Organizations selectByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated
     */
    @Update({
            "update organizations",
            "set name = #{name,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Organizations record);
}