package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Parties;
import org.venuspj.studio.adapter.mybatis.model.PartiesExample;

import java.util.List;

@Mapper
public interface PartiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    @Delete({
            "delete from parties",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    @Insert({
            "insert into parties (party_id, created_at, ",
            "created_by)",
            "values (#{partyId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
            "#{createdBy,jdbcType=VARCHAR})"
    })
    int insert(Parties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    int insertSelective(Parties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    List<Parties> selectByExample(PartiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "party_id, created_at, created_by",
            "from parties",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.PartiesMapper.BaseResultMap")
    Parties selectByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Parties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parties
     *
     * @mbg.generated
     */
    @Update({
            "update parties",
            "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Parties record);
}