package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.People;
import org.venuspj.studio.adapter.mybatis.model.PeopleExample;

import java.util.List;

@Mapper
public interface PeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    @Delete({
            "delete from people",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    @Insert({
            "insert into people (party_id, name, ",
            "created_at, created_by)",
            "values (#{partyId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int insertSelective(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    List<People> selectByExample(PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "party_id, name, created_at, created_by",
            "from people",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.PeopleMapper.BaseResultMap")
    People selectByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    @Update({
            "update people",
            "set name = #{name,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where party_id = #{partyId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(People record);
}