package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Places;
import org.venuspj.studio.adapter.mybatis.model.PlacesExample;

import java.util.List;

@Mapper
public interface PlacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    @Delete({
            "delete from places",
            "where place_id = #{placeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    @Insert({
            "insert into places (place_id, created_at, ",
            "created_by)",
            "values (#{placeId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
            "#{createdBy,jdbcType=VARCHAR})"
    })
    int insert(Places record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    int insertSelective(Places record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    List<Places> selectByExample(PlacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "place_id, created_at, created_by",
            "from places",
            "where place_id = #{placeId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.PlacesMapper.BaseResultMap")
    Places selectByPrimaryKey(Integer placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Places record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table places
     *
     * @mbg.generated
     */
    @Update({
            "update places",
            "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where place_id = #{placeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Places record);
}