package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Players;

public interface PlayersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    @Delete({
        "delete from players",
        "where player_id = #{playerId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    @Insert({
        "insert into players (player_id, player_name, ",
        "created_at, created_by)",
        "values (#{playerId,jdbcType=VARCHAR}, #{playerName,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    int insertSelective(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "player_id, player_name, created_at, created_by",
        "from players",
        "where player_id = #{playerId,jdbcType=VARCHAR}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.PlayersMapper.BaseResultMap")
    Players selectByPrimaryKey(String playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */
    @Update({
        "update players",
        "set player_name = #{playerName,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR}",
        "where player_id = #{playerId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Players record);
}