package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.StudioPlayers;

@Mapper
public interface StudioPlayersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Delete({
        "delete from studio_players",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String studioPlayerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Insert({
        "insert into studio_players (studio_player_id, player_id, ",
        "studio_player_path, studio_player_name_prefix, ",
        "studio_player_name_postfix, display_order_number, ",
        "created_at, created_by, ",
        "studio_player_short_description, studio_player_description)",
        "values (#{studioPlayerId,jdbcType=VARCHAR}, #{playerId,jdbcType=VARCHAR}, ",
        "#{studioPlayerPath,jdbcType=VARCHAR}, #{studioPlayerNamePrefix,jdbcType=VARCHAR}, ",
        "#{studioPlayerNamePostfix,jdbcType=VARCHAR}, #{displayOrderNumber,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR}, ",
        "#{studioPlayerShortDescription,jdbcType=LONGVARCHAR}, #{studioPlayerDescription,jdbcType=LONGVARCHAR})"
    })
    int insert(StudioPlayers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    int insertSelective(StudioPlayers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "studio_player_id, player_id, studio_player_path, studio_player_name_prefix, ",
        "studio_player_name_postfix, display_order_number, created_at, created_by, studio_player_short_description, ",
        "studio_player_description",
        "from studio_players",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.StudioPlayersMapper.ResultMapWithBLOBs")
    StudioPlayers selectByPrimaryKey(String studioPlayerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudioPlayers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Update({
        "update studio_players",
        "set player_id = #{playerId,jdbcType=VARCHAR},",
          "studio_player_path = #{studioPlayerPath,jdbcType=VARCHAR},",
          "studio_player_name_prefix = #{studioPlayerNamePrefix,jdbcType=VARCHAR},",
          "studio_player_name_postfix = #{studioPlayerNamePostfix,jdbcType=VARCHAR},",
          "display_order_number = #{displayOrderNumber,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR},",
          "studio_player_short_description = #{studioPlayerShortDescription,jdbcType=LONGVARCHAR},",
          "studio_player_description = #{studioPlayerDescription,jdbcType=LONGVARCHAR}",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(StudioPlayers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_players
     *
     * @mbg.generated
     */
    @Update({
        "update studio_players",
        "set player_id = #{playerId,jdbcType=VARCHAR},",
          "studio_player_path = #{studioPlayerPath,jdbcType=VARCHAR},",
          "studio_player_name_prefix = #{studioPlayerNamePrefix,jdbcType=VARCHAR},",
          "studio_player_name_postfix = #{studioPlayerNamePostfix,jdbcType=VARCHAR},",
          "display_order_number = #{displayOrderNumber,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR}",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(StudioPlayers record);
}