package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.StudioPlayerMembers;
import org.venuspj.studio.adapter.mybatis.model.StudioPlayerMembersExample;

import java.util.List;

@Mapper
public interface StudioPlayerMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Delete({
            "delete from studio_player_members",
            "where studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String studioPlayerMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Insert({
            "insert into studio_player_members (studio_player_member_id, studio_player_member_name, ",
            "display_order_number, created_at, ",
            "created_by)",
            "values (#{studioPlayerMemberId,jdbcType=VARCHAR}, #{studioPlayerMemberName,jdbcType=VARCHAR}, ",
            "#{displayOrderNumber,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
            "#{createdBy,jdbcType=VARCHAR})"
    })
    int insert(StudioPlayerMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    int insertSelective(StudioPlayerMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    List<StudioPlayerMembers> selectByExample(StudioPlayerMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "studio_player_member_id, studio_player_member_name, display_order_number, created_at, ",
            "created_by",
            "from studio_player_members",
            "where studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.StudioPlayerMembersMapper.BaseResultMap")
    StudioPlayerMembers selectByPrimaryKey(String studioPlayerMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudioPlayerMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_members
     *
     * @mbg.generated
     */
    @Update({
            "update studio_player_members",
            "set studio_player_member_name = #{studioPlayerMemberName,jdbcType=VARCHAR},",
            "display_order_number = #{displayOrderNumber,jdbcType=INTEGER},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(StudioPlayerMembers record);
}