package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.StudioPlayerXMembers;

@Mapper
public interface StudioPlayerXMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    @Delete({
        "delete from studio_player_x_members",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}",
          "and studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("studioPlayerId") String studioPlayerId, @Param("studioPlayerMemberId") String studioPlayerMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    @Insert({
        "insert into studio_player_x_members (studio_player_id, studio_player_member_id, ",
        "created_at, created_by)",
        "values (#{studioPlayerId,jdbcType=VARCHAR}, #{studioPlayerMemberId,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(StudioPlayerXMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    int insertSelective(StudioPlayerXMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "studio_player_id, studio_player_member_id, created_at, created_by",
        "from studio_player_x_members",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}",
          "and studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.StudioPlayerXMembersMapper.BaseResultMap")
    StudioPlayerXMembers selectByPrimaryKey(@Param("studioPlayerId") String studioPlayerId, @Param("studioPlayerMemberId") String studioPlayerMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudioPlayerXMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio_player_x_members
     *
     * @mbg.generated
     */
    @Update({
        "update studio_player_x_members",
        "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR}",
        "where studio_player_id = #{studioPlayerId,jdbcType=VARCHAR}",
          "and studio_player_member_id = #{studioPlayerMemberId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(StudioPlayerXMembers record);
}