package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.TwitterAccounts;
import org.venuspj.studio.adapter.mybatis.model.TwitterAccountsExample;

import java.util.List;

@Mapper
public interface TwitterAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Delete({
            "delete from twitter_accounts",
            "where twitter_accounts_id = #{twitterAccountsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer twitterAccountsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Insert({
            "insert into twitter_accounts (twitter_accounts_id, twitter_id, ",
            "created_at, created_by)",
            "values (#{twitterAccountsId,jdbcType=INTEGER}, #{twitterId,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=VARCHAR})"
    })
    int insert(TwitterAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    int insertSelective(TwitterAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    List<TwitterAccounts> selectByExample(TwitterAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "twitter_accounts_id, twitter_id, created_at, created_by",
            "from twitter_accounts",
            "where twitter_accounts_id = #{twitterAccountsId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.TwitterAccountsMapper.BaseResultMap")
    TwitterAccounts selectByPrimaryKey(Integer twitterAccountsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TwitterAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twitter_accounts
     *
     * @mbg.generated
     */
    @Update({
            "update twitter_accounts",
            "set twitter_id = #{twitterId,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "created_by = #{createdBy,jdbcType=VARCHAR}",
            "where twitter_accounts_id = #{twitterAccountsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TwitterAccounts record);
}