package org.venuspj.studio.adapter.mybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.venuspj.studio.adapter.mybatis.model.Venues;

public interface VenuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Delete({
        "delete from venues",
        "where venue_id = #{venueId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer venueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Insert({
        "insert into venues (venue_id, venue_name_prefix, ",
        "venue_name, venue_name_postfix, ",
        "venue_address, venue_latitude, ",
        "venue_longitude, venue_tel_no, ",
        "venue_twitter, venue_email, ",
        "venue_url, created_at, ",
        "created_by, venue_description)",
        "values (#{venueId,jdbcType=INTEGER}, #{venueNamePrefix,jdbcType=VARCHAR}, ",
        "#{venueName,jdbcType=VARCHAR}, #{venueNamePostfix,jdbcType=VARCHAR}, ",
        "#{venueAddress,jdbcType=VARCHAR}, #{venueLatitude,jdbcType=VARCHAR}, ",
        "#{venueLongitude,jdbcType=VARCHAR}, #{venueTelNo,jdbcType=VARCHAR}, ",
        "#{venueTwitter,jdbcType=VARCHAR}, #{venueEmail,jdbcType=VARCHAR}, ",
        "#{venueUrl,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{venueDescription,jdbcType=LONGVARCHAR})"
    })
    int insert(Venues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    int insertSelective(Venues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "venue_id, venue_name_prefix, venue_name, venue_name_postfix, venue_address, ",
        "venue_latitude, venue_longitude, venue_tel_no, venue_twitter, venue_email, venue_url, ",
        "created_at, created_by, venue_description",
        "from venues",
        "where venue_id = #{venueId,jdbcType=INTEGER}"
    })
    @ResultMap("org.venuspj.studio.adapter.mybatis.mapper.VenuesMapper.ResultMapWithBLOBs")
    Venues selectByPrimaryKey(Integer venueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Venues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Update({
        "update venues",
        "set venue_name_prefix = #{venueNamePrefix,jdbcType=VARCHAR},",
          "venue_name = #{venueName,jdbcType=VARCHAR},",
          "venue_name_postfix = #{venueNamePostfix,jdbcType=VARCHAR},",
          "venue_address = #{venueAddress,jdbcType=VARCHAR},",
          "venue_latitude = #{venueLatitude,jdbcType=VARCHAR},",
          "venue_longitude = #{venueLongitude,jdbcType=VARCHAR},",
          "venue_tel_no = #{venueTelNo,jdbcType=VARCHAR},",
          "venue_twitter = #{venueTwitter,jdbcType=VARCHAR},",
          "venue_email = #{venueEmail,jdbcType=VARCHAR},",
          "venue_url = #{venueUrl,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR},",
          "venue_description = #{venueDescription,jdbcType=LONGVARCHAR}",
        "where venue_id = #{venueId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Venues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbg.generated
     */
    @Update({
        "update venues",
        "set venue_name_prefix = #{venueNamePrefix,jdbcType=VARCHAR},",
          "venue_name = #{venueName,jdbcType=VARCHAR},",
          "venue_name_postfix = #{venueNamePostfix,jdbcType=VARCHAR},",
          "venue_address = #{venueAddress,jdbcType=VARCHAR},",
          "venue_latitude = #{venueLatitude,jdbcType=VARCHAR},",
          "venue_longitude = #{venueLongitude,jdbcType=VARCHAR},",
          "venue_tel_no = #{venueTelNo,jdbcType=VARCHAR},",
          "venue_twitter = #{venueTwitter,jdbcType=VARCHAR},",
          "venue_email = #{venueEmail,jdbcType=VARCHAR},",
          "venue_url = #{venueUrl,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "created_by = #{createdBy,jdbcType=VARCHAR}",
        "where venue_id = #{venueId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Venues record);
}